### ISSUE TITLE
Evmos /metrics/validators not support

### ISSUE THREAD

**Issue by RicoToothless** [solarlabsteam/cosmos-exporter#10]
Evmos is a highly customized chain. `/metrics/wallet` and `/metrics/validator` are fine.

Is it possible to support `/metrics/validators`?

This is my error message

```
Started Cosmos Exporter.
8:54AM INF Config file not provided
8:54AM INF Started with following parameters --bech-account-prefix=evmos --bech-account-pubkey-prefix=evmospub --bech-consensus-node-prefix=evmosvalcons --bech-consensus-node-pubkey-prefix=evmxxxx
8:54AM INF Got network status from Tendermint network=evmos_9001-1
8:54AM INF Using provided denom and coefficient. coefficient=6 denom=aevmos
8:54AM INF Listening address=:9300
8:54AM INF Request processed endpoint=/metrics/wallet?address=xxxxxxxxxxxxx method=GET request-id=exxxx request-time=0.002631239
panic: Int64() out of bound
goroutine 56 [running]:
github.com/cosmos/cosmos-sdk/types.Dec.RoundInt64(0xc000f121a0, 0x31262df1be46351f)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/types/decimal.go:554 +0xb3
main.ValidatorsHandler.func1.1(0x3f, 0x30, 0x1435700)
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:155 +0x50
sort.medianOfThree_func(0xc00009bf90, 0xc000f20f60, 0x3f, 0x30, 0x4e)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:53 +0x3e
sort.doPivot_func(0xc00009bf90, 0xc000f20f60, 0x0, 0x7e, 0xfa523e, 0x7f82357328c0)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:77 +0x53d
sort.quickSort_func(0xc00009bf90, 0xc000f20f60, 0x0, 0x7e, 0xe)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:143 +0x97
sort.Slice(0x1300460, 0xc000ddc888, 0xc00009bf90)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/slice.go:20 +0xe8
main.ValidatorsHandler.func1(0xc000cfe5d4, 0xc000db2a80, 0xc000c64a80, 0xc000ddc5d0)
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:154 +0x3bd
created by main.ValidatorsHandler
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:129 +0x1336
cosmos-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
cosmos-exporter.service: Failed with result 'exit-code'.
cosmos-exporter.service: Scheduled restart job, restart counter is at 1.
```

It seems some issue about Cosmos SDK panic about int64

**Comment by husonghua** [comment]
Exactly the same issue on Sifchain as well.
