### ISSUE TITLE
UTF8 moniker names

### ISSUE THREAD

**Issue by hivefive-space** [solarlabsteam/cosmos-exporter#26]
Hello

The cosmos exporter does not validate non-utf8 moniker names correctly during the requests to /validators 
So if any validator in chain uses non-utf8 character in the moniker - there is no validator who could use your cosmos-exporter tool to monitor his or her node. 

Example:
https://empower.explorers.guru/validator/empowervaloper1a35zftt7z3huc47a35cx2cmdy6yyhqzf2nwtws
Error:
2022/10/23 16:51:07 http: panic serving 157.90.120.132:51016: label moniker: value "\xd1metil" is not valid UTF-8
goroutine 1723524 [running]:
net/http.(*conn).serve.func1(0xc001cba000)
	/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1824 +0x153
panic(0x1351100, 0xc001a250a0)
	/opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:971 +0x499
github.com/prometheus/client_golang/prometheus.(*GaugeVec).With(0xc0017b0290, 0xc001929bf0, 0x1506d61, 0x7)
	/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.8.0/prometheus/gauge.go:228 +0xe5
main.ValidatorsHandler(0x188f820, 0xc001cbe000, 0xc0022f6400, 0xc000fb0e00)
	/home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:228 +0x2e2f
main.Execute.func3(0x188f820, 0xc001cbe000, 0xc0022f6400)
	/home/runner/work/cosmos-exporter/cosmos-exporter/main.go:167 +0x48
net/http.HandlerFunc.ServeHTTP(0xc000f9de70, 0x188f820, 0xc001cbe000, 0xc0022f6400)
	/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0x2185320, 0x188f820, 0xc001cbe000, 0xc0022f6400)
	/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000194460, 0x188f820, 0xc001cbe000, 0xc0022f6400)
	/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc001cba000, 0x1892cf8, 0xc001cb0240)
	/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:3013 +0x39b

**Comment by ryssroad** [comment]
Same error, any updates on it?

**Comment by thenhthang** [comment]
same error, how to fix it.
