### ISSUE TITLE
panic: Int64() out of bound for Cosmos SDK v0.46.10

### ISSUE THREAD

**Issue by ryssroad** [solarlabsteam/cosmos-exporter#37]
On latest version (v0.3.0) service crashes with following error:

```
11:19PM INF Started with following parameters --bech-account-prefix=cascadia --bech-account-pubkey-prefix=cascadiapub --bech-consensus-node-prefix=cascadiavalcons --bech-consensus-node-pubkey-prefix=cascadiavalconspub --bech-validator-prefix=cascadiavaloper --bech-validator-pubkey-prefix=cascadiavaloperpub --denom=aCC --listen-address=:9300 --log-level=info --node=localhost:9190
panic: Int64() out of bound
goroutine 89 [running]:
github.com/cosmos/cosmos-sdk/types.Dec.RoundInt64(0xc00013dd20, 0x1bc16d6713136a8a)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/types/decimal.go:554 +0xb3
main.ValidatorsHandler.func1.1(0x0, 0x60, 0x14367e0)
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:155 +0x85
sort.medianOfThree_func(0xc00156df90, 0xc000e27590, 0x0, 0x60, 0xc0)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:53 +0x3e
sort.doPivot_func(0xc00156df90, 0xc000e27590, 0x0, 0x303, 0xfa523e, 0x7f1a0212a2a0)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:76 +0x4fc
sort.quickSort_func(0xc00156df90, 0xc000e27590, 0x0, 0x303, 0x14)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:143 +0x97
sort.Slice(0x1301460, 0xc00000d350, 0xc00156df90)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/slice.go:20 +0xe8
main.ValidatorsHandler.func1(0xc00059c474, 0xc0005aeb40, 0xc000d62e00, 0xc0011029d8)
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:154 +0x3bd
created by main.ValidatorsHandler
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:129 +0x1336
cosmos-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
cosmos-exporter.service: Failed with result 'exit-code'.
cosmos-exporter.service: Scheduled restart job, restart counter is at 31.
Stopped Cosmos Exporter.
Started Cosmos Exporter.
```
node running on cosmos_sdk_version: v0.46.10 / tendermint v0.34.26

**Comment by ryssroad** [comment]
fixed by https://github.com/solarlabsteam/cosmos-exporter/pull/23
