### ISSUE TITLE
Empty reply for validators metrics

### ISSUE THREAD

**Issue by infiniti8** [solarlabsteam/cosmos-exporter#38]
Hi!

On Entangle blockchain there is a problem with validators metrics, metrics for specific validator is working but for all validators is not working. EOF error in Prometheus.

https://github.com/Entangle-Protocol/entangle-blockchain

Debug:
2023/09/17 19:26:30 http: panic serving 127.0.0.1:43612: Int64() out of bound
goroutine 66 [running]:
net/http.(*conn).serve.func1(0xc0001b45a0)
        /opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1824 +0x153
panic(0x131b540, 0x184db20)
        /opt/hostedtoolcache/go/1.16.5/x64/src/runtime/panic.go:971 +0x499
github.com/cosmos/cosmos-sdk/types.Int.Int64(0xc000eb7a00, 0xc000df5620)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/types/int.go:156 +0xab
main.ValidatorsHandler(0x18908e0, 0xc0001d0380, 0xc0001cc300, 0xc000d13180)
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:256 +0x1e38
main.Execute.func3(0x18908e0, 0xc0001d0380, 0xc0001cc300)
        /home/runner/work/cosmos-exporter/cosmos-exporter/main.go:169 +0x48
net/http.HandlerFunc.ServeHTTP(0xc0000a6890, 0x18908e0, 0xc0001d0380, 0xc0001cc300)
        /opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0x2186320, 0x18908e0, 0xc0001d0380, 0xc0001cc300)
        /opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc00017a380, 0x18908e0, 0xc0001d0380, 0xc0001cc300)
        /opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0001b45a0, 0x1893db8, 0xc0001babc0)
        /opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.16.5/x64/src/net/http/server.go:3013 +0x39b
panic: Int64() out of bound
goroutine 77 [running]:
github.com/cosmos/cosmos-sdk/types.Dec.RoundInt64(0xc000eb7a20, 0x40e0f8)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/types/decimal.go:554 +0xb3
main.ValidatorsHandler.func1.1(0x0, 0x11, 0x14367e0)
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:155 +0x50
sort.medianOfThree_func(0xc000ddff90, 0xc000fc1200, 0x0, 0x11, 0x21)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:53 +0x3e
sort.doPivot_func(0xc000ddff90, 0xc000fc1200, 0x0, 0x22, 0xfa523e, 0x7ff4dd9c0b40)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:80 +0x88
sort.quickSort_func(0xc000ddff90, 0xc000fc1200, 0x0, 0x22, 0xc)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:143 +0x97
sort.Slice(0x1301460, 0xc000efa0d8, 0xc000ddff90)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/slice.go:20 +0xe8
main.ValidatorsHandler.func1(0xc000117500, 0xc000eda8a0, 0xc000d13180, 0xc000119e18)
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:154 +0x3bd
created by main.ValidatorsHandler
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:129 +0x1336

Debug part two:
panic: Int64() out of bound
goroutine 31 [running]:
github.com/cosmos/cosmos-sdk/types.Dec.RoundInt64(0xc000dfa0e0, 0x40e0f8)
        /home/runner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.4/types/decimal.go:554 +0xb3
main.ValidatorsHandler.func1.1(0x0, 0x11, 0x14367e0)
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:155 +0x50
sort.medianOfThree_func(0xc000e33f90, 0xc000fb7ad0, 0x0, 0x11, 0x21)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:53 +0x3e
sort.doPivot_func(0xc000e33f90, 0xc000fb7ad0, 0x0, 0x22, 0x1f4, 0x7fa3895d49d8)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:80 +0x88
sort.quickSort_func(0xc000e33f90, 0xc000fb7ad0, 0x0, 0x22, 0xc)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/zfuncversion.go:143 +0x97
sort.Slice(0x1301460, 0xc000de4348, 0xc000e33f90)
        /opt/hostedtoolcache/go/1.16.5/x64/src/sort/slice.go:20 +0xe8
main.ValidatorsHandler.func1(0xc0005a9110, 0xc0005fe840, 0xc000537c00, 0xc0010e0300)
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:154 +0x3bd
created by main.ValidatorsHandler
        /home/runner/work/cosmos-exporter/cosmos-exporter/validators.go:129 +0x1336

Prometheus config:
  - job_name: 'validator'
    scrape_interval: 15s
    metrics_path: /metrics/validator
    static_configs:
      - targets:
        - ethmvaloper19j4pje5sljgta7t79c0xh6uduc8u7ra0s97pz0
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_address
      - source_labels: [__param_address]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9300

  - job_name: 'validators'
    scrape_interval: 15s
    metrics_path: /metrics/validators
    static_configs:
      - targets: ['localhost:9300']

**Comment by infiniti8** [comment]
the issue is resolved by PR from https://github.com/ad2ien/cosmos-exporter, the problem was in the source code
